wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.3
    framework: huggingface
    huggingface_version: 4.44.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1733623319
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 105
      3:
      - 2
      - 23
      4: 3.11.9
      5: 0.17.3
      6: 4.44.2
      8:
      - 1
      - 5
      13: linux-x86_64
